### PR TITLE
Df/issue116 exercise tree structure

### PR DESCRIPTION
**Pull request by foozebox**

### CODE REVIEW

**Comment by kirjs** [comment]
Please add a screenshot

**Comment by foozebox** [comment]
image

**Comment by foozebox** [comment]
image

**Comment by kirjs** [comment]
Beatiful! Mind adding file/folder icons? Or I can do it myself after merge

**Comment by kirjs** [comment]
Merging, I'll fix the linting errors myself

**Comment by prestonvanloon** [comment]
@kirjs that error should be fixed, try merging in master here.

**Comment by foozebox** [comment]
@kirjs  Added icons and some styling to match no-padding slides here PR: https://github.com/AngularNYC/angular-presentation/pull/153

**Pull request merged**
