### PR TITLE
restart #237 (idk where old branch went rip)

### PR DESCRIPTION
**Pull request by tessaSAC**
Figured out how to grab element off DOM but not where or how to edit it to add data-step and data-intro attributes. Need to make sure it only does it on the mini explanation slide, too (maybe this can be solved hand-in-hand with #423?)

### CODE REVIEW

**Comment by kirjs** [comment]
Create another directive put it on the slide, and do something like this: 
```
slide.isActive.subscribe(active=>{
if(active){
el.setAttribute('data-step', 10)
el.setAttribute('data-intro', 'hi')
} else {
el.removeAttribute('data-step')
el.removeAttribute('data-intro')
}
});
```

**Comment by prestonvanloon** [comment]
Is this still needed now that #469 is up for review?

**Comment by kirjs** [comment]
Is this a dupe of the other one?

**Comment by tessaSAC** [comment]
No, it's no longer needed and yes it's sort of a duplicate because of the commit issues I had last week. I was keeping it open until I could look at the secondary PR again and now I can safely close this one 🙂

**Pull request closed without merging**
